apiVersion: v1
kind: Service
metadata:
  name: bullboard-service
  namespace: checklist
spec:
  type: LoadBalancer
  selector:
    app: bullboard
  ports:
    - port: 80
      targetPort: 3000                     # :contentReference[oaicite:2]{index=2}&#8203;:contentReference[oaicite:3]{index=3}
