apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bullboard-pvc
  namespace: checklist
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
